#pragma once

#define AUTO_SHIFT_REPEAT
#define AUTO_SHIFT_TIMEOUT 160
#define IGNORE_MOD_TAP_INTERRUPT
#define RETRO_SHIFT 500
#define TAPPING_FORCE_HOLD
#define TAPPING_TERM 160
#define UNICODE_SELECTED_MODES UC_LNX
